version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: boilerplate-api
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
  team-api:
    container_name: team-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend
networks:
    backend :
volumes:
  postgres:
    name: api-db