version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: boilerplate-api
    volumes:
      - .docker-data/postgres:/var/lib/postgresql/data